### ISSUE TITLE
[ISSUE] DND 5E 3.0.0+ Compatibility (Deprecation Warnings)

### ISSUE THREAD

**Issue by lipehique** [teroparvinen/foundry-action-pack#46]
Action Pack on DND 5E 3.0.0+ is giving multiple deprecation warnings on token actor selection. Module is working fine, otherwise. 

Foundry Version: 11.315
System Version: DND 5E 3.0.1
Module Version: 11.2
Only module enabled is Action Pack

Steps to reproduce: enable action pack, click on actor token on the canvas. Console will show the following error:
```
Error: The `system.components` property has been deprecated in favor of a standardized `system.properties` property.
Deprecated since Version DnD5e 3.0
Backwards-compatible support will be removed in Version DnD5e 3.2
    at Object.logCompatibilityWarning (commons.js:2059:19)
    at get components [as components] (spell.mjs:171:19)
    at lookupProperty (handlebars.min.js:27:16153)
    at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:20:263)
    at h (handlebars.min.js:27:17870)
    at c (handlebars.min.js:27:6899)
    at Array.<anonymous> (handlebars.min.js:27:7289)
    at Array.c (handlebars.min.js:27:19853)
    at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:11:49)
    at h (handlebars.min.js:27:17870)
```
Module is working fine otherwise.

**Comment by gambit07** [comment]
I added a couple pr's, it's just a few lines to fix
